spring.application.name=project-Music-Streaming-System-New
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MusicSystemDB2;encrypt=true;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=Galaxy@123
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=melodify2025@gmail.com
spring.mail.password=belkwmzukyoubyrf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
spring-boot.run.jvmArguments=-Xms2g -Xmx6g
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=2
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,application/json,image/*
logging.file.name=Melodify.log

